Feature/log out
dhis2/dhis2-android-dataentry pull request #16
Opened 2017-06-08 16:42 UTC by luckytommy

2017-06-15 11:04 UTC, arazabishov requested changes

2017-06-15 11:04 UTC, ArazAbishov commented on app/src/test/java/org/hisp/dhis/android/dataentry/main/MainPresenterUnitTests.java
> +        mainPresenter = new MainPresenterImpl(null, new MockSchedulersProvider(), userRepository);
No tests for presenter.logOut()?

2017-06-15 11:04 UTC, ArazAbishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/MainActivity.java
> +        ProgressDialog dialog = ProgressDialog.show(this, "Logging out", "Deleting all data");
It is better to use string resources instead of hardcoding prompts.

2017-06-15 11:04 UTC, ArazAbishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/MainActivity.java
> +        mainPresenter.logOut();
Doing IO on the main thread.

2017-06-16 07:57 UTC, luckytommy commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/MainActivity.java
> +        mainPresenter.logOut();
This is one instance where it actually makes sense to do IO on the main thread. The user has confirmed log out and the UI should be blocked until log out is complete.

2017-06-16 07:57 UTC, luckytommy commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/MainActivity.java
> +        ProgressDialog dialog = ProgressDialog.show(this, "Logging out", "Deleting all data");
Fixed

2017-06-16 07:58 UTC, luckytommy commented on app/src/test/java/org/hisp/dhis/android/dataentry/main/MainPresenterUnitTests.java
> +        mainPresenter = new MainPresenterImpl(null, new MockSchedulersProvider(), userRepository);
Jira task for this: https://jira.dhis2.org/browse/ANDRODHIS2-486

2017-06-19 11:23 UTC, closed without merging