Implementation of the home fragment
dhis2/dhis2-android-dataentry pull request #2
Opened 2017-02-28 15:01 UTC by luckytommy

2017-03-02 15:25 UTC, arazabishov requested changes
Code review.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/MainRobot.java
> +/*
We don't need to have license headers anymore in the source files.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/MainViewTests.java
> +/*
License header.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +/*
License header.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +    public DatabaseRule databaseRule = new DatabaseRule(ImmediateScheduler.create());
Use trampoline scheduler instead of immediate one.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +        testObserver.assertNoErrors();
Missing assertions on stream completeness. Since observable which . homeEntities() return is hot, stream should never complete.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +
Assertions on whether the stream is complete or not.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +
Assertions on whether the stream is complete or not.

2017-03-02 15:25 UTC, arazabishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +
Assertions on whether the stream is complete or not.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/commons/PerFragment.java
> +/*
License header.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/commons/views/DividerDecoration.java
> +    private final Drawable mDivider;
No need to use m prefix. We have abandoned Hungarian notation.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeFragment.java
> +        getUserComponent().plus(new HomeModule()).inject(this);
Injecting in onCreate() for fragments is dangerous, use onAttach() instead.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeFragment.java
> +        unbinder = ButterKnife.bind(this, view);
It is much more convenient to call Butterknife from onViewCreated(), not onCreateView().

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeFragment.java
> +        super.onViewCreated(view, savedInstanceState);
No need to call super.onViewCreated(), it is a dummy implementation.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryImpl.java
> +                    "(SELECT %s,%s,'%s' AS %s FROM %s " +
Is there any reason to use string formatting instead of regular concatenation?

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeViewModel.java
> +    public static class Columns extends BaseIdentifiableObjectModel.Columns {
ViewModels are not intended to have schema columns within them.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/res/layout/fragment_home.xml
> +        android:id="@+id/home_recyclerview"
We need to follow naming convention for resources and layouts. For example, for layouts is should be:
recyclerview_home. Then it is much easier to search for it.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/res/layout/single_line_list_icon_with_text.xml
> +                style="@style/SingleLineListItemWithIconAndText">
Referencing android style instead of compat.library's one? YOLO.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/res/layout/single_line_list_icon_with_text.xml
> +        android:id="@+id/icon"
Fixing naming convention.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/res/layout/single_line_list_icon_with_text.xml
> +        android:id="@+id/text"
Naming convention.

2017-03-02 15:25 UTC, arazabishov commented on app/src/main/res/values/colors.xml
> +    <color name="color_white">#FFFFFF</color>
Maybe it is better to use the android.R.color.white?

2017-03-02 15:25 UTC, arazabishov commented on app/src/test/java/org/hisp/dhis/android/dataentry/main/home/HomePresenterUnitTest.java
> +
Could be nice to have a test which ensures that updates pushed through repository are getting propagated to the presenter.

2017-03-02 15:27 UTC, luckytommy commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +    public DatabaseRule databaseRule = new DatabaseRule(ImmediateScheduler.create());
Check out in araz feature branch

2017-03-02 15:28 UTC, luckytommy commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
> +        testObserver.assertNoErrors();
add testObserver.assertNotComplete();

2017-03-02 15:45 UTC, luckytommy commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeViewModel.java
> +    public static class Columns extends BaseIdentifiableObjectModel.Columns {
Keeping it as it is for now

2017-03-02 15:54 UTC, luckytommy commented on app/src/main/res/layout/fragment_home.xml
> +        android:id="@+id/home_recyclerview"
Convention: Use subdirs for layouts, prefix with feature name

2017-03-02 15:56 UTC, luckytommy commented on app/src/main/res/layout/single_line_list_icon_with_text.xml
> +                style="@style/SingleLineListItemWithIconAndText">
Fixed

2017-03-02 15:57 UTC, luckytommy commented on app/src/main/res/values/colors.xml
> +    <color name="color_white">#FFFFFF</color>
Will fix

2017-03-02 15:58 UTC, luckytommy commented on app/src/test/java/org/hisp/dhis/android/dataentry/main/home/HomePresenterUnitTest.java
> +
Will fix

2017-03-08 09:33 UTC, luckytommy commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryImpl.java
> +                    "(SELECT %s,%s,'%s' AS %s FROM %s " +
performance

2017-03-13 07:58 UTC, arazabishov approved these changes

2017-03-13 07:58 UTC, merged