Feature/form viewmodels
dhis2/dhis2-android-dataentry pull request #6
Opened 2017-03-21 14:20 UTC by luckytommy

Made some minor changes to Home screen view models / repository

2017-04-05 08:09 UTC, arazabishov requested changes

2017-04-05 08:09 UTC, ArazAbishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
>          testObserver.assertValueCount(1); // One list is returned
No checks on whether stream completes or not. The same applies to errors.

2017-04-05 08:09 UTC, ArazAbishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
>          testObserver.assertValueCount(1); // One list is returned
Okay, after viewing the file I found those assertions at the end. Maybe it could be better to group them?

2017-04-05 08:09 UTC, ArazAbishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeViewModel.java
> +    static class Columns {
Do we need Columns? What about just hardcoding column indices within conversion method?

2017-04-05 12:38 UTC, luckytommy commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
>          testObserver.assertValueCount(1); // One list is returned
Group them how?

2017-04-05 12:53 UTC, luckytommy commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeViewModel.java
> +    static class Columns {
Its not strictly needed, but hardcoded indices will break if we change ordering of results in SQL statements.

2017-04-06 06:58 UTC, ArazAbishov commented on app/src/androidTest/java/org/hisp/dhis/android/dataentry/main/home/HomeRepositoryIntegrationTests.java
>          testObserver.assertValueCount(1); // One list is returned
It is not urgent, but something to consider for readability.

2017-04-06 07:01 UTC, ArazAbishov commented on app/src/main/java/org/hisp/dhis/android/dataentry/main/home/HomeViewModel.java
> +    static class Columns {
Defining static class for that is overkill, it is not being used outside the model right?

2017-04-06 13:51 UTC, luckytommy commented
OK, I have grouped testObserver assertions. Columns stay as discussed. Will you merge?

2017-04-06 13:52 UTC, arazabishov approved these changes

2017-04-06 13:52 UTC, merged